export const overlayBar =
        "typeWindows-1za-n7.withFrame-haYltI.titleBar-AC4pGV.horizontalReverse-3tRjY7.flex-1O1GKY.directionRowReverse-m8IjIq.justifyStart-2NDFzi.alignStretch-DpGPf3",
    overlayDarkener = "app-1q1i1E",
    emojiPicker = "contentWrapper-2txmjs",
    reactionsPicker = "emojiPicker-3PwZFl",
    downloadAttachment = "attachment-33OFj0",
    friendsTab = "theme-dark .container-1D34oG",
    codeBlocks = "code.inline, .markup-2BOw-j code, code",
    messagePopouts = "wrapper-2aW0bm",
    pinnedMessages = "messagesPopoutWrap-1MQ1bW",
    searchResults = "searchResultsWrap-3-pOjs",
    embedBackground = "embedFull-2tM8--",
    blockedMessages = "groupStart-23k01U",
    invites = "wrapper-35wsBm",
    allMessages = "message-2qnXI6",
    inboxPopup = "recentMentionsPopout-3rCiI6";
